name: Build

on:
  pull_request:
  push:
    branches:
      - SCRUM-2-Task-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building application"

      - name: Test
        run: echo "Running tests"
